// <auto-generated />
using CityServicesPortal.Domain.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PetitionsApi.Data;
using System;

namespace PetitionsApi.Migrations
{
    [DbContext(typeof(PetitionsContext))]
    [Migration("20180221195916_AddedStatusAndAdditionalFieldsToPetition")]
    partial class AddedStatusAndAdditionalFieldsToPetition
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CityServicesPortal.Domain.Core.Petition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("PetitionAreaId");

                    b.Property<int>("PetitionUserId");

                    b.Property<int>("PetitionsStatus");

                    b.HasKey("Id");

                    b.HasIndex("PetitionAreaId");

                    b.ToTable("Petitions");
                });

            modelBuilder.Entity("CityServicesPortal.Domain.Core.PetitionArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("PetitionArea");
                });

            modelBuilder.Entity("CityServicesPortal.Domain.Core.Petition", b =>
                {
                    b.HasOne("CityServicesPortal.Domain.Core.PetitionArea", "PetitionArea")
                        .WithMany()
                        .HasForeignKey("PetitionAreaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
